image: node:8.12.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - apt-get update && apt-get install -y libsecret-1-dev
          - printf "@atlassian:registry=${NPM_REGISTRY_URL}\n@atlassiansox:registry=${NPM_REGISTRY_URL}\n//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\n" >> ~/.npmrc
          - yarn --verbose
          - npm run vscode:prepublish
