image: node:8.12.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - apt-get update && apt-get install -y libsecret-1-dev
          - curl -u $NPM_LOGIN:$NPM_TOKEN https://packages.atlassian.com/api/npm/atlassian-npm/auth/atlassian > ~/.npmrc
          - echo "@atlassiansox:registry=https://packages.atlassian.com/api/npm/atlassian-npm/" >> .npmrc
          - echo "@atlassian:registry=https://packages.atlassian.com/api/npm/atlassian-npm/" >> .npmrc
          - yarn --verbose
          - npm run vscode:prepublish
