image: node:8.12.0

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - apt-get update && apt-get install -y libsecret-1-dev
          - yarn
          - npm run vscode:prepublish
